Temporarily disable ML4 and MLX5 again to fix FTBS
The latest version of the rdma-core libraries does not seem to be
compatible with the current version of the MLX4 and MLX5 PMDs, causing
a build failure:

drivers/net/mlx5/mlx5.c: In function 'mlx5_pci_probe':
drivers/net/mlx5/mlx5.c:683:37: error: storage size of 'cs_desc' isn't
     known
  struct ibv_counter_set_description cs_desc;
                                     ^~~~~~~
drivers/net/mlx5/mlx5.c:934:47: error: 'struct ibv_device_attr_ex' has
     no member named 'max_counter_sets'
   priv->counter_set_supported = !!(device_attr.max_counter_sets);
                                               ^
drivers/net/mlx5/mlx5.c:935:3: warning: implicit declaration of function
     'ibv_describe_counter_set'; did you mean 'ibv_destroy_counters'?
     [-Wimplicit-function-declaration]
   ibv_describe_counter_set(ctx, 0, &cs_desc);
   ^~~~~~~~~~~~~~~~~~~~~~~~
   ibv_destroy_counters
drivers/net/mlx5/mlx5.c:935:3: warning: nested extern declaration of
     'ibv_describe_counter_set' [-Wnested-externs]
drivers/net/mlx5/mlx5.c:683:37: warning: unused variable 'cs_desc'
     [-Wunused-variable]
  struct ibv_counter_set_description cs_desc;

Disable the PMDs to fix the immediate build failure until the issue is
resolved properly.

Change-Id: I278ed838d86b5a1111e68651b58603be15fb4ec6
Signed-off-by: Luca Boccassi <luca.boccassi@gmail.com>